# Generated by Django 5.1.6 on 2025-02-17 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applogin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_query', models.TextField()),
                ('chatbot_response', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='classroom',
            name='teacherid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='applogin.teacher'),
        ),
        migrations.AddField(
            model_name='student',
            name='selscore',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='teacherid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='applogin.teacher'),
        ),
        migrations.CreateModel(
            name='Studenttask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskfile', models.FileField(blank=True, null=True, upload_to='studentcompletedtask')),
                ('taskdescription', models.CharField(blank=True, max_length=100, null=True)),
                ('taskmarks', models.IntegerField(blank=True, null=True)),
                ('taskstatus', models.CharField(blank=True, max_length=100, null=True)),
                ('studentid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='applogin.student')),
                ('taskid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='applogin.task')),
            ],
        ),
    ]
