# Generated by Django 5.1.6 on 2025-02-26 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applogin', '0002_chathistory_classroom_teacherid_student_selscore_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='students',
            field=models.ManyToManyField(to='applogin.student'),
        ),
        migrations.RemoveField(
            model_name='parent',
            name='student_id',
        ),
        migrations.AddField(
            model_name='parent',
            name='student_id',
            field=models.ManyToManyField(blank=True, null=True, to='applogin.student'),
        ),
    ]
