# Generated by Django 5.1.3 on 2024-11-27 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applogin', '0003_userprofile_name_alter_userprofile_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('TEACHER', 'Teacher'), ('ADMIN', 'Admin'), ('STUDENT', 'Student'), ('INSTITUTE', 'Institute')], max_length=20),
        ),
        migrations.CreateModel(
            name='Journals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='pdfthumbnail')),
                ('pdfFile', models.ImageField(blank=True, null=True, upload_to='pdfFile')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('viewOption', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
