# Generated by Django 5.1.6 on 2025-02-26 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applogin', '0003_classroom_students_remove_parent_student_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studenttaskcompleted',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taskfile', models.FileField(blank=True, null=True, upload_to='studentcompletedtask')),
                ('taskdescription', models.CharField(blank=True, max_length=100, null=True)),
                ('taskmarks', models.IntegerField(blank=True, null=True)),
                ('taskstatus', models.CharField(blank=True, max_length=100, null=True)),
                ('studentid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='applogin.student')),
                ('taskid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='applogin.task')),
            ],
        ),
    ]
