# Generated by Django 5.1.3 on 2024-11-27 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applogin', '0004_alter_userprofile_user_type_journals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journals',
            name='pdfFile',
            field=models.FileField(blank=True, null=True, upload_to='pdfFile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('INSTITUTE', 'Institute'), ('ADMIN', 'Admin'), ('TEACHER', 'Teacher')], max_length=20),
        ),
    ]
