# Generated by Django 5.1.6 on 2025-03-05 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applogin', '0005_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='student_id',
            field=models.ManyToManyField(blank=True, to='applogin.student'),
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.CharField(blank=True, max_length=100, null=True)),
                ('notification_date', models.DateField(auto_now=True, null=True)),
                ('userid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='applogin.login')),
            ],
        ),
    ]
