# Generated by Django 5.1.3 on 2024-12-06 11:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applogin', '0005_alter_journals_pdffile_alter_userprofile_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='journals',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journals',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('DEACTIVE', 'Deactive'), ('ACTIVE', 'Active')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('TEACHER', 'Teacher'), ('INSTITUTE', 'Institute'), ('STUDENT', 'Student'), ('ADMIN', 'Admin')], max_length=20),
        ),
    ]
