# Generated by Django 5.1.3 on 2024-12-06 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applogin', '0006_journals_created_at_journals_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('DEACTIVE', 'Deactive')], max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('INSTITUTE', 'Institute'), ('ADMIN', 'Admin'), ('TEACHER', 'Teacher'), ('STUDENT', 'Student')], max_length=20),
        ),
    ]
